services:
  runner-cpu-default:
    image: myoung34/github-runner:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RUNNER_SCOPE: org
      ORG_NAME: ${ORG_NAME}
      LABELS: self-hosted,linux,x64,cpu-default
      RUNNER_NAME_PREFIX: ${RUNNER_NAME_PREFIX}-cpu-
      RUNNER_WORKDIR: /tmp/runner/work
      EPHEMERAL: "1"
      DISABLE_AUTO_UPDATE: "1"
      RUN_AS_ROOT: "false"
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    volumes:
      - ./runner-data/cpu:/tmp/runner
      - /var/run/docker.sock:/var/run/docker.sock

  runner-high-mem:
    image: myoung34/github-runner:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RUNNER_SCOPE: org
      ORG_NAME: ${ORG_NAME}
      LABELS: self-hosted,linux,x64,high-mem
      RUNNER_NAME_PREFIX: ${RUNNER_NAME_PREFIX}-hm-
      RUNNER_WORKDIR: /tmp/runner/work
      EPHEMERAL: "1"
      DISABLE_AUTO_UPDATE: "1"
      RUN_AS_ROOT: "false"
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    volumes:
      - ./runner-data/high-mem:/tmp/runner
      - /var/run/docker.sock:/var/run/docker.sock
